// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by: cargo test generate_bindings -- --ignored
// AUTO-GENERATED FILE - DO NOT EDIT
// Generated by: cargo test generate_bindings -- --ignored

// This file has been generated by Specta. DO NOT EDIT.

/**
 * Bank account types
 */
export type AccountType = "checking" | "savings" | "credit_card" | "investment"

/**
 * Bank account entity
 */
export type BankAccount = { id: string; name: string; accountType: string; iban: string | null; bban: string | null; currency: string; balance: string; institutionId: string | null; externalAccountId: string | null; dataSource: string; lastSyncedAt: number | null; interestRate: string | null; hasZoneDesignation: boolean; terminationDate: number | null; 
/**
 * Exclude from portfolio balance (for operational/checking accounts)
 */
excludeFromBalance: boolean; createdAt: number; updatedAt: number }

/**
 * Bank account with institution data (enriched)
 */
export type BankAccountWithInstitution = ({ id: string; name: string; accountType: string; iban: string | null; bban: string | null; currency: string; balance: string; institutionId: string | null; externalAccountId: string | null; dataSource: string; lastSyncedAt: number | null; interestRate: string | null; hasZoneDesignation: boolean; terminationDate: number | null; 
/**
 * Exclude from portfolio balance (for operational/checking accounts)
 */
excludeFromBalance: boolean; createdAt: number; updatedAt: number }) & { institution: Institution | null; effectiveInterestRate: number | null; projectedEarnings: number | null }

/**
 * Bank transaction entity
 */
export type BankTransaction = { id: string; bankAccountId: string; transactionId: string | null; type: string; amount: string; currency: string; description: string | null; counterpartyName: string | null; counterpartyIban: string | null; bookingDate: number; valueDate: number | null; categoryId: string | null; merchantCategoryCode: string | null; remittanceInfo: string | null; variableSymbol: string | null; status: string; dataSource: string; createdAt: number }

/**
 * Bond holding
 */
export type Bond = { id: string; name: string; isin: string; couponValue: string; quantity: string; currency: string; interestRate: string; maturityDate: number | null; createdAt: number; updatedAt: number }

/**
 * User-defined cashflow item (income or expense)
 */
export type CashflowItem = { id: string; name: string; amount: string; currency: string; frequency: string; itemType: string; category: string; createdAt: number; updatedAt: number }

/**
 * Crypto investment holding
 */
export type CryptoInvestment = { id: string; ticker: string; coingeckoId: string; name: string; quantity: string; averagePrice: string }

/**
 * Crypto transaction (buy/sell)
 */
export type CryptoTransaction = { id: string; investmentId: string; type: string; ticker: string; name: string; quantity: string; pricePerUnit: string; currency: string; transactionDate: number; createdAt: number }

/**
 * Data source for accounts and transactions
 */
export type DataSource = "manual" | "csv_import" | "api_sync"

/**
 * User dividend override
 */
export type DividendOverride = { id: string; ticker: string; yearlyDividendSum: string; currency: string; updatedAt: number }

/**
 * Enriched crypto with current price
 */
export type EnrichedCryptoInvestment = { id: string; ticker: string; coingeckoId: string; name: string; quantity: string; averagePrice: string; currentPrice: string; 
/**
 * Original price in its source currency (before conversion to CZK)
 */
originalPrice: string; 
/**
 * Currency of the original price (e.g., USD, EUR)
 */
currency: string; fetchedAt: number | null; 
/**
 * Whether the price is manually overridden
 */
isManualPrice: boolean }

/**
 * Enriched investment with current price data
 */
export type EnrichedStockInvestment = { id: string; ticker: string; companyName: string; quantity: string; averagePrice: string; currentPrice: number; 
/**
 * Original price in its source currency (before conversion to CZK)
 */
originalPrice: string; 
/**
 * Currency of the original price (e.g., USD, EUR)
 */
currency: string; fetchedAt: number | null; isManualPrice: boolean; dividendYield: number; 
/**
 * Original dividend amount before conversion
 */
originalDividendYield: number; dividendCurrency: string; isManualDividend: boolean }

/**
 * Data for creating/updating a bank account
 */
export type InsertBankAccount = { name: string; accountType: string | null; iban: string | null; bban: string | null; currency: string | null; balance: string | null; institutionId: string | null; interestRate: string | null; hasZoneDesignation: boolean | null; terminationDate: number | null; 
/**
 * Exclude from portfolio balance (for operational/checking accounts)
 */
excludeFromBalance: boolean | null }

/**
 * Data for creating/updating a transaction
 */
export type InsertBankTransaction = { bankAccountId: string; transactionId: string | null; type: string; amount: string; currency: string | null; description: string | null; counterpartyName: string | null; counterpartyIban: string | null; bookingDate: number; valueDate: number | null; categoryId: string | null; variableSymbol: string | null; status: string | null }

/**
 * Data for creating/updating bond
 */
export type InsertBond = { name: string; isin: string; couponValue: string; quantity: string | null; currency: string | null; interestRate: string | null; maturityDate: number | null }

/**
 * Data for creating/updating cashflow item
 */
export type InsertCashflowItem = { name: string; amount: string; currency: string | null; frequency: string; itemType: string; category: string }

/**
 * Data for creating crypto investment
 */
export type InsertCryptoInvestment = { ticker: string; coingeckoId: string; name: string; quantity: string | null; averagePrice: string | null }

/**
 * Data for creating crypto transaction
 */
export type InsertCryptoTransaction = { investmentId: string | null; type: string; ticker: string; name: string; quantity: string; pricePerUnit: string; currency: string; transactionDate: number }

/**
 * Data for creating/updating insurance policy
 */
export type InsertInsurancePolicy = { type: string; provider: string; policyName: string; policyNumber: string | null; startDate: number; endDate: number | null; paymentFrequency: string; oneTimePayment: string | null; oneTimePaymentCurrency: string | null; regularPayment: string | null; regularPaymentCurrency: string | null; limits: InsuranceLimit[] | null; notes: string | null; status: string | null }

/**
 * Data for creating transaction
 */
export type InsertInvestmentTransaction = { investmentId: string | null; type: string; ticker: string; companyName: string; quantity: string; pricePerUnit: string; currency: string; transactionDate: number }

/**
 * Data for creating/updating loan
 */
export type InsertLoan = { name: string; principal: string; currency: string | null; interestRate: string | null; interestRateValidityDate: number | null; monthlyPayment: string | null; startDate: number | null; endDate: number | null }

/**
 * Data for creating/updating other asset
 */
export type InsertOtherAsset = { name: string; quantity: string | null; marketPrice: string | null; currency: string | null; averagePurchasePrice: string | null; yieldType: string | null; yieldValue: string | null }

/**
 * Data for creating transaction
 */
export type InsertOtherAssetTransaction = { assetId: string | null; type: string; quantity: string; pricePerUnit: string; currency: string; transactionDate: number }

/**
 * Data for creating/updating real estate
 */
export type InsertRealEstate = { name: string; address: string; type: string; purchasePrice: string | null; purchasePriceCurrency: string | null; marketPrice: string | null; marketPriceCurrency: string | null; monthlyRent: string | null; monthlyRentCurrency: string | null; recurringCosts: RecurringCost[] | null; photos: string[] | null; notes: string | null }

/**
 * Data for creating/updating savings account
 */
export type InsertSavingsAccount = { name: string; balance: string; currency: string | null; interestRate: string | null; hasZoneDesignation: boolean | null; terminationDate: number | null }

/**
 * Data for creating stock investment
 */
export type InsertStockInvestment = { ticker: string; companyName: string; quantity: string | null; averagePrice: string | null }

/**
 * Data for creating a stock tag
 */
export type InsertStockTag = { name: string; color: string | null; groupId: string | null }

/**
 * Data for creating a stock tag group
 */
export type InsertStockTagGroup = { name: string; description: string | null }

/**
 * Data for creating/updating user profile
 */
export type InsertUserProfile = { name: string; surname: string; email: string; menuPreferences: MenuPreferences | null; currency: string | null; language: string | null; excludePersonalRealEstate: boolean | null }

/**
 * Financial institution (bank)
 */
export type Institution = { id: string; name: string; bic: string | null; country: string | null; logoUrl: string | null; createdAt: number }

/**
 * Insurance document (attached contracts, certificates, etc.)
 */
export type InsuranceDocument = { id: string; insuranceId: string; name: string; description: string | null; filePath: string; fileType: string; fileSize: number | null; uploadedAt: number }

/**
 * Insurance limit
 */
export type InsuranceLimit = { title: string; amount: number; currency: string }

/**
 * Insurance policy
 */
export type InsurancePolicy = { id: string; type: string; provider: string; policyName: string; policyNumber: string | null; startDate: number; endDate: number | null; paymentFrequency: string; oneTimePayment: string | null; oneTimePaymentCurrency: string | null; regularPayment: string; regularPaymentCurrency: string; limits: InsuranceLimit[]; notes: string | null; status: string; createdAt: number; updatedAt: number }

/**
 * Investment transaction (buy/sell)
 */
export type InvestmentTransaction = { id: string; investmentId: string; type: string; ticker: string; companyName: string; quantity: string; pricePerUnit: string; currency: string; transactionDate: number; createdAt: number }

/**
 * Loan
 */
export type Loan = { id: string; name: string; principal: string; currency: string; interestRate: string; interestRateValidityDate: number | null; monthlyPayment: string; startDate: number; endDate: number | null; createdAt: number; updatedAt: number }

/**
 * Menu preferences for sidebar visibility
 */
export type MenuPreferences = { savings: boolean; loans: boolean; insurance: boolean; investments: boolean; bonds: boolean; realEstate: boolean; crypto?: boolean; otherAssets?: boolean }

/**
 * Other asset (commodities, collectibles, etc.)
 */
export type OtherAsset = { id: string; name: string; quantity: string; marketPrice: string; currency: string; averagePurchasePrice: string; yieldType: string; yieldValue: string | null; createdAt: number; updatedAt: number }

/**
 * Transaction for other asset
 */
export type OtherAssetTransaction = { id: string; assetId: string; type: string; quantity: string; pricePerUnit: string; currency: string; transactionDate: number; createdAt: number }

/**
 * Current portfolio metrics
 */
export type PortfolioMetrics = { totalSavings: number; totalInvestments: number; totalCrypto: number; totalBonds: number; totalRealEstatePersonal: number; totalRealEstateInvestment: number; totalRealEstate: number; totalOtherAssets: number; totalLiabilities: number; totalAssets: number; netWorth: number }

/**
 * Portfolio metrics history entry
 */
export type PortfolioMetricsHistory = { id: string; totalSavings: string; totalLoansPrincipal: string; totalInvestments: string; totalCrypto: string; totalBonds: string; totalRealEstatePersonal: string; totalRealEstateInvestment: string; totalOtherAssets: string; recordedAt: number }

/**
 * Projection settings for a specific asset type
 */
export type ProjectionSettings = { id: string; assetType: string; yearlyGrowthRate: string; monthlyContribution: string; contributionCurrency: string; enabled: boolean; createdAt?: number; updatedAt?: number }

/**
 * Real estate property
 */
export type RealEstate = { id: string; name: string; address: string; type: string; purchasePrice: string; purchasePriceCurrency: string; marketPrice: string; marketPriceCurrency: string; monthlyRent: string | null; monthlyRentCurrency: string | null; recurringCosts: RecurringCost[]; photos: string[]; notes: string | null; createdAt: number; updatedAt: number }

/**
 * Real estate document (attached contracts, deeds, etc.)
 */
export type RealEstateDocument = { id: string; realEstateId: string; name: string; description: string | null; filePath: string; fileType: string; fileSize: number | null; uploadedAt: number }

/**
 * One-time cost for real estate
 */
export type RealEstateOneTimeCost = { id: string; realEstateId: string; name: string; description: string | null; amount: string; currency: string; date: number; createdAt: number }

/**
 * Individual photo within a batch
 */
export type RealEstatePhoto = { id: string; batchId: string; filePath: string; thumbnailPath: string; createdAt: number }

/**
 * Photo batch (groups photos by date and description)
 */
export type RealEstatePhotoBatch = { id: string; realEstateId: string; photoDate: number; description: string | null; photos: RealEstatePhoto[]; createdAt: number }

/**
 * Recurring cost for real estate
 */
export type RecurringCost = { name: string; amount: number; frequency: string; currency: string | null }

/**
 * Savings account
 */
export type SavingsAccount = { id: string; name: string; balance: string; currency: string; interestRate: string; hasZoneDesignation: boolean; createdAt: number; updatedAt: number; effectiveInterestRate?: number | null; projectedEarnings?: number | null; terminationDate?: number | null }

/**
 * Interest rate zone for tiered accounts
 */
export type SavingsAccountZone = { id: string; savingsAccountId: string; fromAmount: string; toAmount: string | null; interestRate: string; createdAt: number }

/**
 * Stock investment holding
 */
export type StockInvestment = { id: string; ticker: string; companyName: string; quantity: string; averagePrice: string }

/**
 * User price override
 */
export type StockPriceOverride = { id: string; ticker: string; price: string; currency: string; updatedAt: number }

/**
 * Stock tag for categorizing investments (e.g., Growth, Value, Dividend)
 */
export type StockTag = { id: string; name: string; color: string | null; groupId: string | null; createdAt: number }

/**
 * Stock tag group for organizing related tags
 */
export type StockTagGroup = { id: string; name: string; description: string | null; createdAt: number }

/**
 * Per-ticker value history record
 */
export type TickerValueHistory = { ticker: string; recordedAt: number; valueCzk: string; quantity: string; price: string; currency: string }

/**
 * Transaction category
 */
export type TransactionCategory = { id: string; name: string; icon: string | null; color: string | null; parentId: string | null; sortOrder: number; isSystem: boolean; createdAt: number }

/**
 * Filters for querying transactions
 */
export type TransactionFilters = { dateFrom: number | null; dateTo: number | null; categoryId: string | null; txType: string | null; search: string | null; limit: number | null; offset: number | null }

/**
 * Result of transaction query with pagination
 */
export type TransactionQueryResult = { transactions: BankTransaction[]; total: number }

/**
 * Transaction categorization rule
 */
export type TransactionRule = { id: string; name: string; ruleType: string; pattern: string; categoryId: string; priority: number; isActive: boolean; createdAt: number }

/**
 * Transaction status
 */
export type TransactionStatus = "booked" | "pending"

/**
 * Transaction type
 */
export type TransactionType = "credit" | "debit"

/**
 * Data for updating user profile (partial updates)
 */
export type UpdateUserProfile = { name: string | null; surname: string | null; email: string | null; menuPreferences: MenuPreferences | null; currency: string | null; language: string | null; excludePersonalRealEstate: boolean | null }

/**
 * User profile stored in database
 */
export type UserProfile = { id: number; name: string; surname: string; email: string; menuPreferences: MenuPreferences; currency: string; language: string; excludePersonalRealEstate: boolean; createdAt: number }

