import { 
  ShoppingCart,
  Utensils,
  Car,
  Zap,
  Film,
  ShoppingBag,
  Heart,
  Home,
  Briefcase,
  GraduationCap,
  Plane,
  Gift,
  Wallet,
  CreditCard,
  Building,
  Coffee,
  Gamepad2,
  Dumbbell,
  Phone,
  Wifi,
  Fuel,
  Bus,
  Train,
  Baby,
  PawPrint,
  Scissors,
  Shirt,
  PiggyBank,
  ArrowRightLeft,
  TrendingUp,
  Repeat,
  LineChart,
  Hammer,
  MoreHorizontal,
  Landmark,
  Shield,
  type LucideProps,
} from 'lucide-react';
import type { ComponentType } from 'react';

// Map Lucide icon names to components
export const ICON_MAP: Record<string, ComponentType<LucideProps>> = {
  'shopping-cart': ShoppingCart,
  'utensils': Utensils,
  'car': Car,
  'zap': Zap,
  'film': Film,
  'shopping-bag': ShoppingBag,
  'heart': Heart,
  'home': Home,
  'briefcase': Briefcase,
  'graduation-cap': GraduationCap,
  'plane': Plane,
  'gift': Gift,
  'wallet': Wallet,
  'credit-card': CreditCard,
  'building': Building,
  'coffee': Coffee,
  'gamepad-2': Gamepad2,
  'dumbbell': Dumbbell,
  'phone': Phone,
  'wifi': Wifi,
  'fuel': Fuel,
  'bus': Bus,
  'train': Train,
  'baby': Baby,
  'paw-print': PawPrint,
  'scissors': Scissors,
  'shirt': Shirt,
  // New category icons
  'piggy-bank': PiggyBank,
  'arrows-right-left': ArrowRightLeft,
  'trending-up': TrendingUp,
  'repeat': Repeat,
  'line-chart': LineChart,
  'hammer': Hammer,
  'more-horizontal': MoreHorizontal,
  'landmark': Landmark,
  'shield': Shield,
};
